/* THE CHUNK-RECORD FIXTURE, REGENERATED FROM A NAMED COMMIT — a tool; prints, and fails only on --check.
 *
 *     node tests/fixture-chunks.cjs [sha=769b1a3] [--check] [--write]
 *
 * econ-check's "'#mine,4242' chunk records 8-12 are identical to the pre-M5 snapshot" compares against
 * tests/fixtures/m5-pre-chunks-4242.json. That file landed in b46b6e2, AFTER M5's generator edit
 * (f582443), so nothing in the repo showed it was taken on a pre-M5 build — and a snapshot taken on
 * the changed build cannot catch an rng-order break the change itself made. This serves
 * `git show <sha>:index.html` in place of index.html (as /.fixture-<sha>.html at the repo root, so
 * `assets/` resolves), streams chunks 8-12 with the same camera walk econ-check uses, and compares the
 * records with the committed fixture byte for byte. `--write` replaces the fixture with `{source, chunks}`.
 */
const fs = require('fs'), path = require('path'), { execFileSync } = require('child_process');
const H = require('./mine-harness.cjs');
const sha = (process.argv.slice(2).find((a) => !a.startsWith('--')) || '769b1a3');
const FIX = path.join(H.ROOT, 'tests', 'fixtures', 'm5-pre-chunks-4242.json');
(async () => {
  const html = execFileSync('git', ['show', sha + ':index.html'], { cwd: H.ROOT, maxBuffer: 64 << 20 }).toString('utf8');
  const tmp = path.join(H.ROOT, '.fixture-' + sha + '.html');
  fs.writeFileSync(tmp, html);
  const E = await H.start();
  let code = 0;
  try {
    const b = await E.boot('#mine,4242', 390, 844, { file: '/.fixture-' + sha + '.html' });
    await H.waitMine(b.page);
    const rec = await b.page.evaluate(async () => {
      const g = window.__game, s = g.state, cs = s.substrate.cellSize, cc = s.config.mine.chunkCols;
      for (const ci of [8, 12]) {
        g.mine.lookAt((ci + 0.5) * cc * cs, s.substrate.surfaceY + 300);
        for (let i = 0; i < 40 && !s.mineChunks[ci]; i++) await new Promise((r) => setTimeout(r, 100));
      }
      const out = {};
      for (const ci of [8, 9, 10, 11, 12]) out[ci] = s.mineChunks[ci] ? JSON.parse(JSON.stringify(s.mineChunks[ci])) : null;
      return out;
    });
    const raw = JSON.parse(fs.readFileSync(FIX, 'utf8'));
    const snap = raw.chunks || raw;
    const diff = [8, 9, 10, 11, 12].filter((ci) => JSON.stringify(rec[ci]) !== JSON.stringify(snap[ci]));
    const all = [8, 9, 10, 11, 12].every((ci) => rec[ci]);
    console.log(`${sha}: chunks 8-12 ${all ? 'generated' : 'MISSING'}; vs the committed fixture: ${diff.length ? 'DIFFER ' + diff.join(',') : 'identical'}`);
    if (process.argv.includes('--write')) {
      fs.writeFileSync(FIX, JSON.stringify({ source: sha, note: 'regenerated by tests/fixture-chunks.cjs from `git show ' + sha + ':index.html`', chunks: rec }));
      console.log('wrote', path.relative(H.ROOT, FIX));
    }
    if (process.argv.includes('--check') && (diff.length || !all)) code = 1;
    await b.ctx.close();
  } finally { await E.close(); fs.unlinkSync(tmp); }
  process.exit(code);
})();
